### ISSUE TITLE
Plus icon small and in the wrong place.

### ISSUE THREAD

**Issue by NickdeDycker** [wagtail/wagtail-condensedinlinepanel#47]
Hi,

I've (surprisingly) not seen any open issues mentioning this. The plus icon to add a new field is very small and easily overlooked. It's also not very user-friendly. Here is how to current add-icon looks like.
![image](https://user-images.githubusercontent.com/7197942/42691157-29e5a9b6-86a7-11e8-8fd8-6a8452346e84.png)

I propose at least one of the following:

Center the button and make it bigger:
![image](https://user-images.githubusercontent.com/7197942/42691371-01848c20-86a8-11e8-8f19-923a1a54cee5.png)

Align it to the left and make it a button, just like how wagtail itself does it (this button looks horrible, but imagine the same button wagtail uses):
![image](https://user-images.githubusercontent.com/7197942/42691447-5d2d917a-86a8-11e8-89b9-032cd374ad5e.png)

I look forward to your responses :)

**Comment by Adrian-Turjak** [comment]
I agree that we probably should make the secondary plus buttons a tiny bit bigger, the main part of the problem here is that the standard plus button is missing (see #48 ) due to a css bug.

It should (and used to before the css issue) look like this:
![screenshot from 2018-07-16 11-35-04](https://user-images.githubusercontent.com/6404853/42739489-5dd9b338-88ec-11e8-9e99-479ceaa36f3e.png)

While we fix #48 we can make the secondary buttons a tiny bit bigger, but the idea with them is that they aren't as prominent.
