### ISSUE TITLE
Checkbox field is automatically unselected

### ISSUE THREAD

**Issue by martey** [wagtail/wagtail-condensedinlinepanel#59]
When using wagtail-condensedinlinepanel with wagtailmenus, the "Allow sub-menu" checkbox option appears unselected regardless of its state in the database. I believe that this might affect all checkboxes in CondensedInlinePanels.

This looks to be the same bug reported in https://github.com/rkhleics/wagtailmenus/issues/311; the consensus there was that this was a bug in wagtail-condensedinlinepanel.

#### Software versions:
  - wagtail-condensedinlinepanel 0.5.2
  - wagtailmenus 2.13
  - wagtail 2.4

**Comment by acerix** [comment]
The issue is that the value gets formatted with `widget.format_value` but `CheckboxInput.format_value` returns `None` when it's value is `True`.

https://github.com/wagtail/wagtail-condensedinlinepanel/blob/master/condensedinlinepanel/edit_handlers.py#L147

https://github.com/django/django/blob/master/django/forms/widgets.py#L517
